import type { GameCard, GameState } from '~/shared/types/game'
const key = 'perfilGameState'
const initial = (): GameState => ({ usedAnswers: [], history: [], score: 0, cardsPlayed: 0, currentCard: null, revealedClues: 0, revealedClueIndexes: [], roundFinished: false, currentCardPoints: 20, selectedCategories: [], selectedDifficulties: [] })
export function useGame() {
  const state = useState<GameState>('perfil-state', initial); const hydrated = useState('perfil-hydrated', () => false); const loading = ref(false); const error = ref(''); const generationMode = useState<'ai-fallback' | 'fallback'>('perfil-generation-mode', () => 'ai-fallback')
  const persist = () => { if (import.meta.client) localStorage.setItem(key, JSON.stringify(state.value)) }
  const hydrate = () => { if (!import.meta.client || hydrated.value) return; try { const raw = localStorage.getItem(key); if (raw) { const saved = JSON.parse(raw); state.value = { ...initial(), ...saved, history: saved.history || [], revealedClueIndexes: saved.revealedClueIndexes || [] } } } catch { localStorage.removeItem(key) } hydrated.value = true }
  const revealClue = (index: number) => { if (!state.value.currentCard || state.value.roundFinished || state.value.revealedClueIndexes.includes(index)) return; state.value.revealedClueIndexes.push(index); state.value.revealedClues = state.value.revealedClueIndexes.length; state.value.currentCardPoints = Math.max(1, 20 - state.value.revealedClues); persist() }
  const finishRound = () => { if (!state.value.currentCard || state.value.roundFinished) return; state.value.score += state.value.currentCardPoints; state.value.cardsPlayed++; state.value.roundFinished = true; state.value.history = [{ category: state.value.currentCard.category, answer: state.value.currentCard.answer, difficulty: state.value.currentCard.difficulty, points: state.value.currentCardPoints }, ...state.value.history]; persist() }
  const requestCard = async () => { if (loading.value) return false; loading.value = true; error.value = ''; try { const card = await $fetch<GameCard>('/api/cards', { method: 'POST', body: { usedAnswers: state.value.usedAnswers, generationMode: generationMode.value, categories: state.value.selectedCategories, difficulties: state.value.selectedDifficulties } }); state.value.currentCard = card; state.value.revealedClues = 0; state.value.revealedClueIndexes = []; state.value.currentCardPoints = 20; state.value.roundFinished = false; state.value.usedAnswers = [...state.value.usedAnswers, card.answer].slice(-100); persist(); return true } catch { error.value = 'Não foi possível gerar uma nova carta.'; return false } finally { loading.value = false } }
  const resetGame = () => { state.value = initial(); if (import.meta.client) localStorage.removeItem(key) }; onMounted(hydrate); return { state, loading, error, generationMode, hydrate, persist, revealClue, finishRound, requestCard, resetGame }
}
