<script setup lang="ts">
const { state, loading, error, requestCard, revealClue, finishRound, resetGame } = useGame(); const answerVisible = ref(false)
const start = async () => { answerVisible.value = false; await requestCard() }; const newCard = async () => { if (state.value.currentCard && !state.value.roundFinished && !window.confirm('A rodada atual será descartada. Continuar?')) return; await start() }; const correct = () => { if (window.confirm(`Confirmar acerto por ${state.value.currentCardPoints} pontos?`)) finishRound() }; const newGame = () => { if (window.confirm('Começar um novo jogo?')) { resetGame(); start() } }; onMounted(() => { if (!state.value.currentCard) start() })
</script>
<style scoped>
.mobile-filters{display:block}.desktop-filters{display:none}
@media(min-width:761px){.mobile-filters{display:none}.desktop-filters{display:block}.main-layout{grid-template-columns:minmax(0,1fr) minmax(300px,340px)}.main-column{min-width:0}.sidebar{display:flex;flex-direction:column;gap:16px}.desktop-filters .filters-card{margin:0}.sidebar .history-panel{margin-top:0}}
</style>
<template><div class="app-shell"><header class="topbar"><BrandLockup /><button class="new-game-button" @click="newGame">Novo jogo</button></header><main class="main-layout"><div class="main-column"><div class="mobile-filters"><FilterSettings /></div><div class="intro"><DecorativeSpark class="intro-spark intro-spark-yellow" tone="yellow" /><div class="intro-copy"><span class="eyebrow">RODADA {{ state.cardsPlayed + (state.currentCard ? 1 : 0) }}</span><h2>Qual é a palavra?</h2></div><DecorativeSpark class="intro-spark intro-spark-coral" tone="coral" /></div><div v-if="loading" class="state-card loading-state"><div class="spinner" /><h2>Gerando nova carta...</h2></div><div v-else-if="error" class="state-card error-state"><h2>Algo deu errado</h2><p>{{ error }}</p><button class="primary-button" @click="start">Tentar novamente</button></div><GameCard v-else-if="state.currentCard" :card="state.currentCard" :revealed="state.revealedClues" :revealed-indexes="state.revealedClueIndexes" :answer-visible="answerVisible" :points="state.currentCardPoints" @toggle-answer="answerVisible = !answerVisible" @reveal-clue="revealClue" /><div v-else class="state-card"><h2>Pronto para jogar?</h2><button class="primary-button" @click="start">Começar partida</button></div></div><aside class="sidebar"><div class="desktop-filters"><FilterSettings /></div><HistoryPanel :history="state.history" /><GameControls :round-finished="state.roundFinished" :loading="loading" @correct="correct" @new-card="newCard" /></aside></main><footer>As dicas são geradas para cada partida e ficam salvas apenas neste navegador.</footer></div></template>
